Create function to randomize serial number
AlexTelon/FlexiCharge-Admin-GUI pull request #146
Opened 2023-09-27 14:24 UTC by vikjoh1

## Description
Added a function to randomize unique serial numbers when adding a charger to a charger station. 

## Screenshots
![image](https://github.com/AlexTelon/FlexiCharge-Admin-GUI/assets/91786266/4d554ce7-4990-425d-849f-b772d366d336)

## Type of PR
- [x] Feature
- [ ] Bugfix
- [ ] Documentation
- [ ] Test
- [ ] Code refactor

## Did you write tests?
- [ ] Yes
- [x] No
- [ ] No, I need help

## If you wrote tests, did they pass?
- [ ] Yes
- [ ] No
- [ ] No, I need help

## In which environment did you test?
- [x] Development
- [x] Production (backend API)
- [ ] Didn't test

## steps for code reviewers
- [ ] Go to the charger stations page
- [ ] Click manage chargers
- [ ] Click add chargers
- [ ] Make sure that it works to add a charger and that it looks good

Closes #95

2023-09-27 16:40 UTC, Ville-Wilson approved these changes
LGTM!

2023-10-03 13:03 UTC, WinterBoii approved these changes

2023-10-06 19:34 UTC, eejebring requested changes
Can you preserve the the serial-number input field? In-case you need to input a specific one? So essentially just pre-fill the input field.
Also, this my be overkill but consider using: https://www.npmjs.com/package/uuidv4

2023-10-09 09:11 UTC, eejebring approved these changes
LGTM

2023-10-09 13:58 UTC, merged