remove charge prices
AlexTelon/FlexiCharge-Admin-GUI pull request #172
Opened 2023-10-08 10:02 UTC by Issa-morad

## Description
Briefly descripe the PR.

## Screenshots
Add if necessary.
Copy paste should work.

## Type of PR
- [ ] Feature
- [ ] Bugfix
- [ ] Documentation
- [ ] Test
- [ ] Code refactor

## Did you write tests?
- [ ] Yes
- [ ] No
- [ ] No, I need help

## If you wrote tests, did they pass?
- [ ] Yes
- [ ] No
- [ ] No, I need help

## In which environment did you test?
- [ ] Development
- [ ] Production (backend API)
- [ ] Didn't test

## steps for code reviewers
### example steps (change for your PR):
- [ ] Click on the Active Chargers button
- [ ] Try to edit a charger
- [ ] Refresh the page
- [ ] Make sure that it works

2023-10-08 10:06 UTC, Issa-morad commented
remove charge point price field

2023-10-08 12:23 UTC, WinterBoii submitted a review, later dismissed

2023-10-08 12:23 UTC, WinterBoii commented on react-app/src/dependencyContainer.ts
> +import AuthenticationProvider from './remote-access/mock/AuthenticationProvider';
Dont commit dependancy container if changing from mock to remote and vice versa

2023-10-08 15:07 UTC, Issa-morad commented on react-app/src/dependencyContainer.ts
> +import AuthenticationProvider from './remote-access/mock/AuthenticationProvider';
ok

2023-10-08 15:30 UTC, vikjoh1 requested changes
Looks good! But you should also remove the price field in the charger-stations mock data.

2023-10-12 08:36 UTC, vikjoh1 approved these changes
LGTM!

2023-10-12 08:39 UTC, merged