163 rename all charegeing station references to charege point
AlexTelon/FlexiCharge-Admin-GUI pull request #176
Opened 2023-10-10 12:48 UTC by WinterBoii

## Description
Changed station to chargerpoint

## Screenshots
Add if necessary.
Copy paste should work.

## Type of PR
- [ ] Feature
- [ ] Bugfix
- [ ] Documentation
- [ ] Test
- [ ] Code refactor

## Did you write tests?
- [ ] Yes
- [ ] No
- [ ] No, I need help

## If you wrote tests, did they pass?
- [ ] Yes
- [ ] No
- [ ] No, I need help

## In which environment did you test?
- [ ] Development
- [ ] Production (backend API)
- [ ] Didn't test

## steps for code reviewers
### example steps (change for your PR):
- [ ] Click on the Active Charger Points button
- [ ] Make sure that its Charger Points

2023-10-11 09:18 UTC, eejebring commented
I seem to experience some type errors like ```stations.location is undefined```
And also the variable should be named chargePoint... if you have time.

2023-10-11 09:37 UTC, vikjoh1 commented
@eejebring I believe these errors you get has to do with that backend changed the name of ```location``` to ```coordinates```. 
I got the same errors in any branch yesterday. However, it has been changed back to ```location``` again, so try to remove the docker container and then build it again.

2023-10-11 09:40 UTC, vikjoh1 requested changes
Looks good! However, you have missed to rename it in some places. if you ```ctrl+shift+f``` in VS code and search "charger station" you will see where it is ;)

2023-10-11 17:12 UTC, Ville-Wilson approved these changes
LGTM! 👍

2023-10-11 18:06 UTC, eejebring commented
![image](https://github.com/AlexTelon/FlexiCharge-Admin-GUI/assets/83876708/46f6cd42-dae0-4411-95b6-f21b056270fa)
only the edit modal left from what I can see

2023-10-11 21:55 UTC, vikjoh1 requested changes
Is it ```charge-point``` or ```chargePoint```? Because it's named different in some components. Also, when adding a charge point, ```station price``` should be ```charge-point price``` and ```station name``` should be ```charge-point name```?

![image](https://github.com/AlexTelon/FlexiCharge-Admin-GUI/assets/91786266/9fe7290b-64ce-4c65-83ff-2f98be290e95)

And personally, I think ```add point``` should be changed to ```add charge-point```

2023-10-12 07:57 UTC, eejebring commented
...Cannot find any UI place where I can see the Charge-points named ChargePoint

2023-10-12 08:41 UTC, vikjoh1 requested changes

2023-10-12 08:41 UTC, vikjoh1 commented on react-app/src/components/pages/chargers/page-components/AddChargerDialog.tsx
> +      <DialogTitle>Add Chargers to a chargePoint</DialogTitle>
here :)

![image](https://github.com/AlexTelon/FlexiCharge-Admin-GUI/assets/91786266/17b119a2-1309-447d-92cb-d24fa6b4631c)

2023-10-12 09:18 UTC, merged